version: '2'
services:
  aur-builder:
    image: ullebe1/aur-build-server
    restart: always
    volumes:
      - "./packagecache:/var/cache/pacman/ulrepo:z"
      - "./builddir:/var/lib/aurbuild/:rw"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    privileged: true
  repo-server:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./packagecache:/usr/share/nginx/html:z"
      - "${PWD}/default.conf:/etc/nginx/conf.d/default.conf:ro"
    security_opt:
      - label:disable
  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
